// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package dm_pasteleria.fac_ventas_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;

@SuppressWarnings("unused")

/**
 * Job: fac_ventas Purpose: <br>
 * Description: <br>
 * 
 * @author user@talend.com
 * @version 8.0.1.20211109_1610
 * @status
 */
public class fac_ventas implements TalendJob {

	protected static void logIgnoredError(String message, Throwable cause) {
		System.err.println(message);
		if (cause != null) {
			cause.printStackTrace();
		}

	}

	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}

	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	private final static String utf8Charset = "UTF-8";

	// contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String, String> propertyTypes = new java.util.HashMap<>();

		public PropertiesWithType(java.util.Properties properties) {
			super(properties);
		}

		public PropertiesWithType() {
			super();
		}

		public void setContextType(String key, String type) {
			propertyTypes.put(key, type);
		}

		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}

	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();

	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties) {
			super(properties);
		}

		public ContextProperties() {
			super();
		}

		public void synchronizeContext() {

		}

		// if the stored or passed value is "<TALEND_NULL>" string, it mean null
		public String getStringValue(String key) {
			String origin_value = this.getProperty(key);
			if (NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY.equals(origin_value)) {
				return null;
			}
			return origin_value;
		}

	}

	protected ContextProperties context = new ContextProperties(); // will be instanciated by MS.

	public ContextProperties getContext() {
		return this.context;
	}

	private final String jobVersion = "0.1";
	private final String jobName = "fac_ventas";
	private final String projectName = "DM_PASTELERIA";
	public Integer errorCode = null;
	private String currentComponent = "";

	private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
	private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();

	private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
	private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
	public final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();

	private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";

	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(),
					new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	public void setDataSourceReferences(List serviceReferences) throws Exception {

		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		java.util.Map<String, javax.sql.DataSource> dataSources = new java.util.HashMap<String, javax.sql.DataSource>();

		for (java.util.Map.Entry<String, javax.sql.DataSource> entry : BundleUtils
				.getServices(serviceReferences, javax.sql.DataSource.class).entrySet()) {
			dataSources.put(entry.getKey(), entry.getValue());
			talendDataSources.put(entry.getKey(), new routines.system.TalendDataSource(entry.getValue()));
		}

		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}

	private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
	private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

	public String getExceptionStackTrace() {
		if ("failure".equals(this.getStatus())) {
			errorMessagePS.flush();
			return baos.toString();
		}
		return null;
	}

	private Exception exception;

	public Exception getException() {
		if ("failure".equals(this.getStatus())) {
			return this.exception;
		}
		return null;
	}

	private class TalendException extends Exception {

		private static final long serialVersionUID = 1L;

		private java.util.Map<String, Object> globalMap = null;
		private Exception e = null;
		private String currentComponent = null;
		private String virtualComponentName = null;

		public void setVirtualComponentName(String virtualComponentName) {
			this.virtualComponentName = virtualComponentName;
		}

		private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
			this.currentComponent = errorComponent;
			this.globalMap = globalMap;
			this.e = e;
		}

		public Exception getException() {
			return this.e;
		}

		public String getCurrentComponent() {
			return this.currentComponent;
		}

		public String getExceptionCauseMessage(Exception e) {
			Throwable cause = e;
			String message = null;
			int i = 10;
			while (null != cause && 0 < i--) {
				message = cause.getMessage();
				if (null == message) {
					cause = cause.getCause();
				} else {
					break;
				}
			}
			if (null == message) {
				message = e.getClass().getName();
			}
			return message;
		}

		@Override
		public void printStackTrace() {
			if (!(e instanceof TalendException || e instanceof TDieException)) {
				if (virtualComponentName != null && currentComponent.indexOf(virtualComponentName + "_") == 0) {
					globalMap.put(virtualComponentName + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				}
				globalMap.put(currentComponent + "_ERROR_MESSAGE", getExceptionCauseMessage(e));
				System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
			}
			if (!(e instanceof TDieException)) {
				if (e instanceof TalendException) {
					e.printStackTrace();
				} else {
					e.printStackTrace();
					e.printStackTrace(errorMessagePS);
					fac_ventas.this.exception = e;
				}
			}
			if (!(e instanceof TalendException)) {
				try {
					for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
						if (m.getName().compareTo(currentComponent + "_error") == 0) {
							m.invoke(fac_ventas.this, new Object[] { e, currentComponent, globalMap });
							break;
						}
					}

					if (!(e instanceof TDieException)) {
					}
				} catch (Exception e) {
					this.e.printStackTrace();
				}
			}
		}
	}

	public void tWaitForFile_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tWaitForFile_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFileInputDelimited_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tWaitForFile_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tMap_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap)
			throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tWaitForFile_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tDBOutput_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tWaitForFile_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tLogRow_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tWaitForFile_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tFileCopy_1_error(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		end_Hash.put(errorComponent, System.currentTimeMillis());

		status = "failure";

		tFileCopy_1_onSubJobError(exception, errorComponent, globalMap);
	}

	public void tWaitForFile_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public void tFileCopy_1_onSubJobError(Exception exception, String errorComponent,
			final java.util.Map<String, Object> globalMap) throws TalendException {

		resumeUtil.addLog("SYSTEM_LOG", "NODE:" + errorComponent, "", Thread.currentThread().getId() + "", "FATAL", "",
				exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception), "");

	}

	public static class row2Struct implements routines.system.IPersistableRow<row2Struct> {
		final static byte[] commonByteArrayLock_DM_PASTELERIA_fac_ventas = new byte[0];
		static byte[] commonByteArray_DM_PASTELERIA_fac_ventas = new byte[0];

		public BigDecimal ID_TIEMPO;

		public BigDecimal getID_TIEMPO() {
			return this.ID_TIEMPO;
		}

		public BigDecimal ID_PRODUCTO;

		public BigDecimal getID_PRODUCTO() {
			return this.ID_PRODUCTO;
		}

		public BigDecimal ID_CLIENTE;

		public BigDecimal getID_CLIENTE() {
			return this.ID_CLIENTE;
		}

		public BigDecimal ID_SUCURSAL;

		public BigDecimal getID_SUCURSAL() {
			return this.ID_SUCURSAL;
		}

		public BigDecimal CANTIDAD;

		public BigDecimal getCANTIDAD() {
			return this.CANTIDAD;
		}

		public BigDecimal TOTAL;

		public BigDecimal getTOTAL() {
			return this.TOTAL;
		}

		public String FECHA_CARGA;

		public String getFECHA_CARGA() {
			return this.FECHA_CARGA;
		}

		public String SISTEMA_CARGA;

		public String getSISTEMA_CARGA() {
			return this.SISTEMA_CARGA;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DM_PASTELERIA_fac_ventas.length) {
					if (length < 1024 && commonByteArray_DM_PASTELERIA_fac_ventas.length == 0) {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[1024];
					} else {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length);
				strReturn = new String(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private String readString(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DM_PASTELERIA_fac_ventas.length) {
					if (length < 1024 && commonByteArray_DM_PASTELERIA_fac_ventas.length == 0) {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[1024];
					} else {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[2 * length];
					}
				}
				unmarshaller.readFully(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length);
				strReturn = new String(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private void writeString(String str, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DM_PASTELERIA_fac_ventas) {

				try {

					int length = 0;

					this.ID_TIEMPO = (BigDecimal) dis.readObject();

					this.ID_PRODUCTO = (BigDecimal) dis.readObject();

					this.ID_CLIENTE = (BigDecimal) dis.readObject();

					this.ID_SUCURSAL = (BigDecimal) dis.readObject();

					this.CANTIDAD = (BigDecimal) dis.readObject();

					this.TOTAL = (BigDecimal) dis.readObject();

					this.FECHA_CARGA = readString(dis);

					this.SISTEMA_CARGA = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				} catch (ClassNotFoundException eCNFE) {
					throw new RuntimeException(eCNFE);

				}

			}

		}

		public void readData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_DM_PASTELERIA_fac_ventas) {

				try {

					int length = 0;

					this.ID_TIEMPO = (BigDecimal) dis.readObject();

					this.ID_PRODUCTO = (BigDecimal) dis.readObject();

					this.ID_CLIENTE = (BigDecimal) dis.readObject();

					this.ID_SUCURSAL = (BigDecimal) dis.readObject();

					this.CANTIDAD = (BigDecimal) dis.readObject();

					this.TOTAL = (BigDecimal) dis.readObject();

					this.FECHA_CARGA = readString(dis);

					this.SISTEMA_CARGA = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				} catch (ClassNotFoundException eCNFE) {
					throw new RuntimeException(eCNFE);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// BigDecimal

				dos.writeObject(this.ID_TIEMPO);

				// BigDecimal

				dos.writeObject(this.ID_PRODUCTO);

				// BigDecimal

				dos.writeObject(this.ID_CLIENTE);

				// BigDecimal

				dos.writeObject(this.ID_SUCURSAL);

				// BigDecimal

				dos.writeObject(this.CANTIDAD);

				// BigDecimal

				dos.writeObject(this.TOTAL);

				// String

				writeString(this.FECHA_CARGA, dos);

				// String

				writeString(this.SISTEMA_CARGA, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeData(org.jboss.marshalling.Marshaller dos) {
			try {

				// BigDecimal

				dos.writeObject(this.ID_TIEMPO);

				// BigDecimal

				dos.writeObject(this.ID_PRODUCTO);

				// BigDecimal

				dos.writeObject(this.ID_CLIENTE);

				// BigDecimal

				dos.writeObject(this.ID_SUCURSAL);

				// BigDecimal

				dos.writeObject(this.CANTIDAD);

				// BigDecimal

				dos.writeObject(this.TOTAL);

				// String

				writeString(this.FECHA_CARGA, dos);

				// String

				writeString(this.SISTEMA_CARGA, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("ID_TIEMPO=" + String.valueOf(ID_TIEMPO));
			sb.append(",ID_PRODUCTO=" + String.valueOf(ID_PRODUCTO));
			sb.append(",ID_CLIENTE=" + String.valueOf(ID_CLIENTE));
			sb.append(",ID_SUCURSAL=" + String.valueOf(ID_SUCURSAL));
			sb.append(",CANTIDAD=" + String.valueOf(CANTIDAD));
			sb.append(",TOTAL=" + String.valueOf(TOTAL));
			sb.append(",FECHA_CARGA=" + FECHA_CARGA);
			sb.append(",SISTEMA_CARGA=" + SISTEMA_CARGA);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row2Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class fac_ventaStruct implements routines.system.IPersistableRow<fac_ventaStruct> {
		final static byte[] commonByteArrayLock_DM_PASTELERIA_fac_ventas = new byte[0];
		static byte[] commonByteArray_DM_PASTELERIA_fac_ventas = new byte[0];

		public BigDecimal ID_TIEMPO;

		public BigDecimal getID_TIEMPO() {
			return this.ID_TIEMPO;
		}

		public BigDecimal ID_PRODUCTO;

		public BigDecimal getID_PRODUCTO() {
			return this.ID_PRODUCTO;
		}

		public BigDecimal ID_CLIENTE;

		public BigDecimal getID_CLIENTE() {
			return this.ID_CLIENTE;
		}

		public BigDecimal ID_SUCURSAL;

		public BigDecimal getID_SUCURSAL() {
			return this.ID_SUCURSAL;
		}

		public BigDecimal CANTIDAD;

		public BigDecimal getCANTIDAD() {
			return this.CANTIDAD;
		}

		public BigDecimal TOTAL;

		public BigDecimal getTOTAL() {
			return this.TOTAL;
		}

		public String FECHA_CARGA;

		public String getFECHA_CARGA() {
			return this.FECHA_CARGA;
		}

		public String SISTEMA_CARGA;

		public String getSISTEMA_CARGA() {
			return this.SISTEMA_CARGA;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DM_PASTELERIA_fac_ventas.length) {
					if (length < 1024 && commonByteArray_DM_PASTELERIA_fac_ventas.length == 0) {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[1024];
					} else {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length);
				strReturn = new String(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private String readString(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DM_PASTELERIA_fac_ventas.length) {
					if (length < 1024 && commonByteArray_DM_PASTELERIA_fac_ventas.length == 0) {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[1024];
					} else {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[2 * length];
					}
				}
				unmarshaller.readFully(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length);
				strReturn = new String(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private void writeString(String str, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DM_PASTELERIA_fac_ventas) {

				try {

					int length = 0;

					this.ID_TIEMPO = (BigDecimal) dis.readObject();

					this.ID_PRODUCTO = (BigDecimal) dis.readObject();

					this.ID_CLIENTE = (BigDecimal) dis.readObject();

					this.ID_SUCURSAL = (BigDecimal) dis.readObject();

					this.CANTIDAD = (BigDecimal) dis.readObject();

					this.TOTAL = (BigDecimal) dis.readObject();

					this.FECHA_CARGA = readString(dis);

					this.SISTEMA_CARGA = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				} catch (ClassNotFoundException eCNFE) {
					throw new RuntimeException(eCNFE);

				}

			}

		}

		public void readData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_DM_PASTELERIA_fac_ventas) {

				try {

					int length = 0;

					this.ID_TIEMPO = (BigDecimal) dis.readObject();

					this.ID_PRODUCTO = (BigDecimal) dis.readObject();

					this.ID_CLIENTE = (BigDecimal) dis.readObject();

					this.ID_SUCURSAL = (BigDecimal) dis.readObject();

					this.CANTIDAD = (BigDecimal) dis.readObject();

					this.TOTAL = (BigDecimal) dis.readObject();

					this.FECHA_CARGA = readString(dis);

					this.SISTEMA_CARGA = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				} catch (ClassNotFoundException eCNFE) {
					throw new RuntimeException(eCNFE);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// BigDecimal

				dos.writeObject(this.ID_TIEMPO);

				// BigDecimal

				dos.writeObject(this.ID_PRODUCTO);

				// BigDecimal

				dos.writeObject(this.ID_CLIENTE);

				// BigDecimal

				dos.writeObject(this.ID_SUCURSAL);

				// BigDecimal

				dos.writeObject(this.CANTIDAD);

				// BigDecimal

				dos.writeObject(this.TOTAL);

				// String

				writeString(this.FECHA_CARGA, dos);

				// String

				writeString(this.SISTEMA_CARGA, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeData(org.jboss.marshalling.Marshaller dos) {
			try {

				// BigDecimal

				dos.writeObject(this.ID_TIEMPO);

				// BigDecimal

				dos.writeObject(this.ID_PRODUCTO);

				// BigDecimal

				dos.writeObject(this.ID_CLIENTE);

				// BigDecimal

				dos.writeObject(this.ID_SUCURSAL);

				// BigDecimal

				dos.writeObject(this.CANTIDAD);

				// BigDecimal

				dos.writeObject(this.TOTAL);

				// String

				writeString(this.FECHA_CARGA, dos);

				// String

				writeString(this.SISTEMA_CARGA, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("ID_TIEMPO=" + String.valueOf(ID_TIEMPO));
			sb.append(",ID_PRODUCTO=" + String.valueOf(ID_PRODUCTO));
			sb.append(",ID_CLIENTE=" + String.valueOf(ID_CLIENTE));
			sb.append(",ID_SUCURSAL=" + String.valueOf(ID_SUCURSAL));
			sb.append(",CANTIDAD=" + String.valueOf(CANTIDAD));
			sb.append(",TOTAL=" + String.valueOf(TOTAL));
			sb.append(",FECHA_CARGA=" + FECHA_CARGA);
			sb.append(",SISTEMA_CARGA=" + SISTEMA_CARGA);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(fac_ventaStruct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public static class row1Struct implements routines.system.IPersistableRow<row1Struct> {
		final static byte[] commonByteArrayLock_DM_PASTELERIA_fac_ventas = new byte[0];
		static byte[] commonByteArray_DM_PASTELERIA_fac_ventas = new byte[0];

		public BigDecimal id_tiempo;

		public BigDecimal getId_tiempo() {
			return this.id_tiempo;
		}

		public BigDecimal id_producto;

		public BigDecimal getId_producto() {
			return this.id_producto;
		}

		public BigDecimal id_cliente;

		public BigDecimal getId_cliente() {
			return this.id_cliente;
		}

		public BigDecimal id_sucursal;

		public BigDecimal getId_sucursal() {
			return this.id_sucursal;
		}

		public BigDecimal cantidad;

		public BigDecimal getCantidad() {
			return this.cantidad;
		}

		public BigDecimal total;

		public BigDecimal getTotal() {
			return this.total;
		}

		public String fecha_carga;

		public String getFecha_carga() {
			return this.fecha_carga;
		}

		public String sistema_carga;

		public String getSistema_carga() {
			return this.sistema_carga;
		}

		private String readString(ObjectInputStream dis) throws IOException {
			String strReturn = null;
			int length = 0;
			length = dis.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DM_PASTELERIA_fac_ventas.length) {
					if (length < 1024 && commonByteArray_DM_PASTELERIA_fac_ventas.length == 0) {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[1024];
					} else {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[2 * length];
					}
				}
				dis.readFully(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length);
				strReturn = new String(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private String readString(org.jboss.marshalling.Unmarshaller unmarshaller) throws IOException {
			String strReturn = null;
			int length = 0;
			length = unmarshaller.readInt();
			if (length == -1) {
				strReturn = null;
			} else {
				if (length > commonByteArray_DM_PASTELERIA_fac_ventas.length) {
					if (length < 1024 && commonByteArray_DM_PASTELERIA_fac_ventas.length == 0) {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[1024];
					} else {
						commonByteArray_DM_PASTELERIA_fac_ventas = new byte[2 * length];
					}
				}
				unmarshaller.readFully(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length);
				strReturn = new String(commonByteArray_DM_PASTELERIA_fac_ventas, 0, length, utf8Charset);
			}
			return strReturn;
		}

		private void writeString(String str, ObjectOutputStream dos) throws IOException {
			if (str == null) {
				dos.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				dos.writeInt(byteArray.length);
				dos.write(byteArray);
			}
		}

		private void writeString(String str, org.jboss.marshalling.Marshaller marshaller) throws IOException {
			if (str == null) {
				marshaller.writeInt(-1);
			} else {
				byte[] byteArray = str.getBytes(utf8Charset);
				marshaller.writeInt(byteArray.length);
				marshaller.write(byteArray);
			}
		}

		public void readData(ObjectInputStream dis) {

			synchronized (commonByteArrayLock_DM_PASTELERIA_fac_ventas) {

				try {

					int length = 0;

					this.id_tiempo = (BigDecimal) dis.readObject();

					this.id_producto = (BigDecimal) dis.readObject();

					this.id_cliente = (BigDecimal) dis.readObject();

					this.id_sucursal = (BigDecimal) dis.readObject();

					this.cantidad = (BigDecimal) dis.readObject();

					this.total = (BigDecimal) dis.readObject();

					this.fecha_carga = readString(dis);

					this.sistema_carga = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				} catch (ClassNotFoundException eCNFE) {
					throw new RuntimeException(eCNFE);

				}

			}

		}

		public void readData(org.jboss.marshalling.Unmarshaller dis) {

			synchronized (commonByteArrayLock_DM_PASTELERIA_fac_ventas) {

				try {

					int length = 0;

					this.id_tiempo = (BigDecimal) dis.readObject();

					this.id_producto = (BigDecimal) dis.readObject();

					this.id_cliente = (BigDecimal) dis.readObject();

					this.id_sucursal = (BigDecimal) dis.readObject();

					this.cantidad = (BigDecimal) dis.readObject();

					this.total = (BigDecimal) dis.readObject();

					this.fecha_carga = readString(dis);

					this.sistema_carga = readString(dis);

				} catch (IOException e) {
					throw new RuntimeException(e);

				} catch (ClassNotFoundException eCNFE) {
					throw new RuntimeException(eCNFE);

				}

			}

		}

		public void writeData(ObjectOutputStream dos) {
			try {

				// BigDecimal

				dos.writeObject(this.id_tiempo);

				// BigDecimal

				dos.writeObject(this.id_producto);

				// BigDecimal

				dos.writeObject(this.id_cliente);

				// BigDecimal

				dos.writeObject(this.id_sucursal);

				// BigDecimal

				dos.writeObject(this.cantidad);

				// BigDecimal

				dos.writeObject(this.total);

				// String

				writeString(this.fecha_carga, dos);

				// String

				writeString(this.sistema_carga, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public void writeData(org.jboss.marshalling.Marshaller dos) {
			try {

				// BigDecimal

				dos.writeObject(this.id_tiempo);

				// BigDecimal

				dos.writeObject(this.id_producto);

				// BigDecimal

				dos.writeObject(this.id_cliente);

				// BigDecimal

				dos.writeObject(this.id_sucursal);

				// BigDecimal

				dos.writeObject(this.cantidad);

				// BigDecimal

				dos.writeObject(this.total);

				// String

				writeString(this.fecha_carga, dos);

				// String

				writeString(this.sistema_carga, dos);

			} catch (IOException e) {
				throw new RuntimeException(e);
			}

		}

		public String toString() {

			StringBuilder sb = new StringBuilder();
			sb.append(super.toString());
			sb.append("[");
			sb.append("id_tiempo=" + String.valueOf(id_tiempo));
			sb.append(",id_producto=" + String.valueOf(id_producto));
			sb.append(",id_cliente=" + String.valueOf(id_cliente));
			sb.append(",id_sucursal=" + String.valueOf(id_sucursal));
			sb.append(",cantidad=" + String.valueOf(cantidad));
			sb.append(",total=" + String.valueOf(total));
			sb.append(",fecha_carga=" + fecha_carga);
			sb.append(",sistema_carga=" + sistema_carga);
			sb.append("]");

			return sb.toString();
		}

		/**
		 * Compare keys
		 */
		public int compareTo(row1Struct other) {

			int returnValue = -1;

			return returnValue;
		}

		private int checkNullsAndCompare(Object object1, Object object2) {
			int returnValue = 0;
			if (object1 instanceof Comparable && object2 instanceof Comparable) {
				returnValue = ((Comparable) object1).compareTo(object2);
			} else if (object1 != null && object2 != null) {
				returnValue = compareStrings(object1.toString(), object2.toString());
			} else if (object1 == null && object2 != null) {
				returnValue = 1;
			} else if (object1 != null && object2 == null) {
				returnValue = -1;
			} else {
				returnValue = 0;
			}

			return returnValue;
		}

		private int compareStrings(String string1, String string2) {
			return string1.compareTo(string2);
		}

	}

	public void tWaitForFile_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tWaitForFile_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				row1Struct row1 = new row1Struct();
				fac_ventaStruct fac_venta = new fac_ventaStruct();
				row2Struct row2 = new row2Struct();

				/**
				 * [tWaitForFile_1 begin ] start
				 */

				int NB_ITERATE_tFileInputDelimited_1 = 0; // for statistics

				ok_Hash.put("tWaitForFile_1", false);
				start_Hash.put("tWaitForFile_1", System.currentTimeMillis());

				currentComponent = "tWaitForFile_1";

				int tos_count_tWaitForFile_1 = 0;

				class Util_tWaitForFile_1 {

					private boolean flagt = false;

					private java.util.regex.Pattern fileNamePatternt = null;
					private java.util.List<String> list;

					public java.util.List<String> getFiles() {
						setFiles();
						return list;
					}

					public Util_tWaitForFile_1() {
						this.list = new java.util.ArrayList<String>();
					}

					public void addFile(java.io.File file) {
						this.list.add(file.getPath());
					}

					void setFiles() {
						String directoryt = "C:/Users/rober/Desktop/paste,eria/ventas/Pendientes";
						String filemaskt = "*.csv" + "$";

						if (filemaskt.indexOf("^") == -1) {
							filemaskt = "^" + filemaskt;
						}
						if (!(filemaskt.lastIndexOf(".*$") == -1) && filemaskt.lastIndexOf("*.*$") == -1) {
							filemaskt = filemaskt.substring(0, filemaskt.length() - 3) + "$";
							flagt = true;
						} else {
							filemaskt = java.util.regex.Pattern.compile("[*]").matcher(filemaskt).replaceAll(".*");
						}

						boolean case_sensitivet = true;
						fileNamePatternt = java.util.regex.Pattern.compile(filemaskt);
						if (!case_sensitivet) {
							fileNamePatternt = java.util.regex.Pattern.compile(filemaskt,
									java.util.regex.Pattern.CASE_INSENSITIVE);
						}
						java.io.File filet = new java.io.File(directoryt);
						filet.listFiles(new java.io.FilenameFilter() {

							public boolean accept(java.io.File dir, String name) {
								java.io.File file = new java.io.File(dir, name);
								if (file.isFile()) {
									String fileNamet = name;
									if (flagt == true) {
										if (!(fileNamet.indexOf(".") == -1)) {
											if (fileNamePatternt.matcher(fileNamet.substring(0, fileNamet.indexOf(".")))
													.find()) {
												addFile(file);

											}
										} else {
											if (fileNamePatternt.matcher(fileNamet).find()) {
												addFile(file);
											}
										}
									} else {
										if (fileNamePatternt.matcher(fileNamet).find()) {
											addFile(file);
										}
									}

									return true;
								}
								return false;
							}

						});

					}

					java.util.List<java.io.File> getCreatedFiles(java.util.List<String> originalFiles,
							java.util.List<String> fetchOneTimeFiles) {
						java.util.List<java.io.File> newCreatedFiles = new java.util.ArrayList<java.io.File>();
						String[] array = originalFiles.toArray(new String[] {});
						for (String file : fetchOneTimeFiles) {
							int index = java.util.Arrays.binarySearch(array, file);
							if (index < 0) {
								newCreatedFiles.add(new java.io.File(file));
							}
						}
						return newCreatedFiles;
					}

				}

				Util_tWaitForFile_1 util_tWaitForFile_1 = new Util_tWaitForFile_1();
				java.util.List<String> originalFiles_tWaitForFile_1 = util_tWaitForFile_1.getFiles();

				int count_tWaitForFile_1 = 0;

				while (true) {
					boolean found_tWaitForFile_1 = false;
					util_tWaitForFile_1 = new Util_tWaitForFile_1();

					java.util.List<String> fetchFilesOneTime_tWaitForFile_1 = util_tWaitForFile_1.getFiles();

					List<String> intersectionList = new java.util.ArrayList<String>();

					for (String cachedFile : originalFiles_tWaitForFile_1) {
						if (fetchFilesOneTime_tWaitForFile_1.contains(cachedFile)) {
							intersectionList.add(cachedFile);
						}
					}

					util_tWaitForFile_1 = new Util_tWaitForFile_1();
					originalFiles_tWaitForFile_1 = intersectionList;
					if (globalMap.get("tWaitForFile_1_CREATED_FILE") != null) {
						globalMap.remove("tWaitForFile_1_CREATED_FILE");
					}
					java.util.Collections.sort(originalFiles_tWaitForFile_1);
					java.util.List<java.io.File> newCreatedFiles_tWaitForFile_1 = util_tWaitForFile_1
							.getCreatedFiles(originalFiles_tWaitForFile_1, fetchFilesOneTime_tWaitForFile_1);

					for (int i = 0; i < newCreatedFiles_tWaitForFile_1.size(); i++) {
						java.io.File file_tWaitForFile_1 = newCreatedFiles_tWaitForFile_1.get(i);

						globalMap.put("tWaitForFile_1_FILENAME", file_tWaitForFile_1.getName());
						globalMap.put("tWaitForFile_1_CREATED_FILE", file_tWaitForFile_1.getAbsolutePath());
						found_tWaitForFile_1 = true;
						originalFiles_tWaitForFile_1.add(file_tWaitForFile_1.getPath());
						break;
					}

					count_tWaitForFile_1++;

					globalMap.put("tWaitForFile_1_CURRENT_ITERATION", count_tWaitForFile_1);

					if (!found_tWaitForFile_1) {

						Thread.sleep(1 * 1000);
						continue;
					}

					/**
					 * [tWaitForFile_1 begin ] stop
					 */

					/**
					 * [tWaitForFile_1 main ] start
					 */

					currentComponent = "tWaitForFile_1";

					tos_count_tWaitForFile_1++;

					/**
					 * [tWaitForFile_1 main ] stop
					 */

					/**
					 * [tWaitForFile_1 process_data_begin ] start
					 */

					currentComponent = "tWaitForFile_1";

					/**
					 * [tWaitForFile_1 process_data_begin ] stop
					 */
					NB_ITERATE_tFileInputDelimited_1++;

					if (execStat) {
						runStat.updateStatOnConnection("row2", 3, 0);
					}

					if (execStat) {
						runStat.updateStatOnConnection("row1", 3, 0);
					}

					if (execStat) {
						runStat.updateStatOnConnection("OnComponentOk1", 3, 0);
					}

					if (execStat) {
						runStat.updateStatOnConnection("fac_venta", 3, 0);
					}

					if (execStat) {
						runStat.updateStatOnConnection("iterate1", 1, "exec" + NB_ITERATE_tFileInputDelimited_1);
						// Thread.sleep(1000);
					}

					/**
					 * [tLogRow_1 begin ] start
					 */

					ok_Hash.put("tLogRow_1", false);
					start_Hash.put("tLogRow_1", System.currentTimeMillis());

					currentComponent = "tLogRow_1";

					if (execStat) {
						runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "row2");
					}

					int tos_count_tLogRow_1 = 0;

					///////////////////////

					class Util_tLogRow_1 {

						String[] des_top = { ".", ".", "-", "+" };

						String[] des_head = { "|=", "=|", "-", "+" };

						String[] des_bottom = { "'", "'", "-", "+" };

						String name = "";

						java.util.List<String[]> list = new java.util.ArrayList<String[]>();

						int[] colLengths = new int[8];

						public void addRow(String[] row) {

							for (int i = 0; i < 8; i++) {
								if (row[i] != null) {
									colLengths[i] = Math.max(colLengths[i], row[i].length());
								}
							}
							list.add(row);
						}

						public void setTableName(String name) {

							this.name = name;
						}

						public StringBuilder format() {

							StringBuilder sb = new StringBuilder();

							sb.append(print(des_top));

							int totals = 0;
							for (int i = 0; i < colLengths.length; i++) {
								totals = totals + colLengths[i];
							}

							// name
							sb.append("|");
							int k = 0;
							for (k = 0; k < (totals + 7 - name.length()) / 2; k++) {
								sb.append(' ');
							}
							sb.append(name);
							for (int i = 0; i < totals + 7 - name.length() - k; i++) {
								sb.append(' ');
							}
							sb.append("|\n");

							// head and rows
							sb.append(print(des_head));
							for (int i = 0; i < list.size(); i++) {

								String[] row = list.get(i);

								java.util.Formatter formatter = new java.util.Formatter(new StringBuilder());

								StringBuilder sbformat = new StringBuilder();
								sbformat.append("|%1$-");
								sbformat.append(colLengths[0]);
								sbformat.append("s");

								sbformat.append("|%2$-");
								sbformat.append(colLengths[1]);
								sbformat.append("s");

								sbformat.append("|%3$-");
								sbformat.append(colLengths[2]);
								sbformat.append("s");

								sbformat.append("|%4$-");
								sbformat.append(colLengths[3]);
								sbformat.append("s");

								sbformat.append("|%5$-");
								sbformat.append(colLengths[4]);
								sbformat.append("s");

								sbformat.append("|%6$-");
								sbformat.append(colLengths[5]);
								sbformat.append("s");

								sbformat.append("|%7$-");
								sbformat.append(colLengths[6]);
								sbformat.append("s");

								sbformat.append("|%8$-");
								sbformat.append(colLengths[7]);
								sbformat.append("s");

								sbformat.append("|\n");

								formatter.format(sbformat.toString(), (Object[]) row);

								sb.append(formatter.toString());
								if (i == 0)
									sb.append(print(des_head)); // print the head
							}

							// end
							sb.append(print(des_bottom));
							return sb;
						}

						private StringBuilder print(String[] fillChars) {
							StringBuilder sb = new StringBuilder();
							// first column
							sb.append(fillChars[0]);
							for (int i = 0; i < colLengths[0] - fillChars[0].length() + 1; i++) {
								sb.append(fillChars[2]);
							}
							sb.append(fillChars[3]);

							for (int i = 0; i < colLengths[1] - fillChars[3].length() + 1; i++) {
								sb.append(fillChars[2]);
							}
							sb.append(fillChars[3]);
							for (int i = 0; i < colLengths[2] - fillChars[3].length() + 1; i++) {
								sb.append(fillChars[2]);
							}
							sb.append(fillChars[3]);
							for (int i = 0; i < colLengths[3] - fillChars[3].length() + 1; i++) {
								sb.append(fillChars[2]);
							}
							sb.append(fillChars[3]);
							for (int i = 0; i < colLengths[4] - fillChars[3].length() + 1; i++) {
								sb.append(fillChars[2]);
							}
							sb.append(fillChars[3]);
							for (int i = 0; i < colLengths[5] - fillChars[3].length() + 1; i++) {
								sb.append(fillChars[2]);
							}
							sb.append(fillChars[3]);
							for (int i = 0; i < colLengths[6] - fillChars[3].length() + 1; i++) {
								sb.append(fillChars[2]);
							}
							sb.append(fillChars[3]);

							// last column
							for (int i = 0; i < colLengths[7] - fillChars[1].length() + 1; i++) {
								sb.append(fillChars[2]);
							}
							sb.append(fillChars[1]);
							sb.append("\n");
							return sb;
						}

						public boolean isTableEmpty() {
							if (list.size() > 1)
								return false;
							return true;
						}
					}
					Util_tLogRow_1 util_tLogRow_1 = new Util_tLogRow_1();
					util_tLogRow_1.setTableName("tLogRow_1");
					util_tLogRow_1.addRow(new String[] { "ID_TIEMPO", "ID_PRODUCTO", "ID_CLIENTE", "ID_SUCURSAL",
							"CANTIDAD", "TOTAL", "FECHA_CARGA", "SISTEMA_CARGA", });
					StringBuilder strBuffer_tLogRow_1 = null;
					int nb_line_tLogRow_1 = 0;
///////////////////////    			

					/**
					 * [tLogRow_1 begin ] stop
					 */

					/**
					 * [tDBOutput_1 begin ] start
					 */

					ok_Hash.put("tDBOutput_1", false);
					start_Hash.put("tDBOutput_1", System.currentTimeMillis());

					currentComponent = "tDBOutput_1";

					if (execStat) {
						runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "fac_venta");
					}

					int tos_count_tDBOutput_1 = 0;

					int nb_line_tDBOutput_1 = 0;
					int nb_line_update_tDBOutput_1 = 0;
					int nb_line_inserted_tDBOutput_1 = 0;
					int nb_line_deleted_tDBOutput_1 = 0;
					int nb_line_rejected_tDBOutput_1 = 0;

					int tmp_batchUpdateCount_tDBOutput_1 = 0;

					int deletedCount_tDBOutput_1 = 0;
					int updatedCount_tDBOutput_1 = 0;
					int insertedCount_tDBOutput_1 = 0;
					int rowsToCommitCount_tDBOutput_1 = 0;
					int rejectedCount_tDBOutput_1 = 0;

					boolean whetherReject_tDBOutput_1 = false;

					java.sql.Connection conn_tDBOutput_1 = null;

					// optional table
					String dbschema_tDBOutput_1 = null;
					String tableName_tDBOutput_1 = null;
					String driverClass_tDBOutput_1 = "oracle.jdbc.OracleDriver";

					java.lang.Class.forName(driverClass_tDBOutput_1);
					String url_tDBOutput_1 = null;
					url_tDBOutput_1 = "jdbc:oracle:thin:@" + "127.0.0.1" + ":" + "1521" + ":" + "xe";
					String dbUser_tDBOutput_1 = "dmPasteleria";

					final String decryptedPassword_tDBOutput_1 = routines.system.PasswordEncryptUtil.decryptPassword(
							"enc:routine.encryption.key.v1:26wFVnHP5/bhIGNrRAR35CsF2MP5yE1mgpeszsDqD1n+Crf0c0UMtQ==");

					String dbPwd_tDBOutput_1 = decryptedPassword_tDBOutput_1;
					dbschema_tDBOutput_1 = "";

					conn_tDBOutput_1 = java.sql.DriverManager.getConnection(url_tDBOutput_1, dbUser_tDBOutput_1,
							dbPwd_tDBOutput_1);
					resourceMap.put("conn_tDBOutput_1", conn_tDBOutput_1);
					conn_tDBOutput_1.setAutoCommit(false);
					int commitEvery_tDBOutput_1 = 10000;
					int commitCounter_tDBOutput_1 = 0;
					int batchSize_tDBOutput_1 = 10000;
					int batchSizeCounter_tDBOutput_1 = 0;
					int count_tDBOutput_1 = 0;

					if (dbschema_tDBOutput_1 == null || dbschema_tDBOutput_1.trim().length() == 0) {
						tableName_tDBOutput_1 = ("FAC_VENTAS");
					} else {
						tableName_tDBOutput_1 = dbschema_tDBOutput_1 + "." + ("FAC_VENTAS");
					}
					String insert_tDBOutput_1 = "INSERT INTO " + tableName_tDBOutput_1
							+ " (ID_TIEMPO,ID_PRODUCTO,ID_CLIENTE,ID_SUCURSAL,CANTIDAD,TOTAL,FECHA_CARGA,SISTEMA_CARGA) VALUES (?,?,?,?,?,?,?,?)";

					java.sql.PreparedStatement pstmt_tDBOutput_1 = conn_tDBOutput_1
							.prepareStatement(insert_tDBOutput_1);
					resourceMap.put("pstmt_tDBOutput_1", pstmt_tDBOutput_1);

					/**
					 * [tDBOutput_1 begin ] stop
					 */

					/**
					 * [tMap_1 begin ] start
					 */

					ok_Hash.put("tMap_1", false);
					start_Hash.put("tMap_1", System.currentTimeMillis());

					currentComponent = "tMap_1";

					if (execStat) {
						runStat.updateStatOnConnection(resourceMap, iterateId, 0, 0, "row1");
					}

					int tos_count_tMap_1 = 0;

// ###############################
// # Lookup's keys initialization
// ###############################        

// ###############################
// # Vars initialization
					class Var__tMap_1__Struct {
					}
					Var__tMap_1__Struct Var__tMap_1 = new Var__tMap_1__Struct();
// ###############################

// ###############################
// # Outputs initialization
					fac_ventaStruct fac_venta_tmp = new fac_ventaStruct();
// ###############################

					/**
					 * [tMap_1 begin ] stop
					 */

					/**
					 * [tFileInputDelimited_1 begin ] start
					 */

					ok_Hash.put("tFileInputDelimited_1", false);
					start_Hash.put("tFileInputDelimited_1", System.currentTimeMillis());

					currentComponent = "tFileInputDelimited_1";

					int tos_count_tFileInputDelimited_1 = 0;

					final routines.system.RowState rowstate_tFileInputDelimited_1 = new routines.system.RowState();

					int nb_line_tFileInputDelimited_1 = 0;
					org.talend.fileprocess.FileInputDelimited fid_tFileInputDelimited_1 = null;
					int limit_tFileInputDelimited_1 = -1;
					try {

						Object filename_tFileInputDelimited_1 = ((String) globalMap.get("tWaitForFile_1_CREATED_FILE"));
						if (filename_tFileInputDelimited_1 instanceof java.io.InputStream) {

							int footer_value_tFileInputDelimited_1 = 0, random_value_tFileInputDelimited_1 = -1;
							if (footer_value_tFileInputDelimited_1 > 0 || random_value_tFileInputDelimited_1 > 0) {
								throw new java.lang.Exception(
										"When the input source is a stream,footer and random shouldn't be bigger than 0.");
							}

						}
						try {
							fid_tFileInputDelimited_1 = new org.talend.fileprocess.FileInputDelimited(
									((String) globalMap.get("tWaitForFile_1_CREATED_FILE")), "US-ASCII", ";", "\n",
									false, 1, 0, limit_tFileInputDelimited_1, -1, false);
						} catch (java.lang.Exception e) {
							globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE", e.getMessage());

							System.err.println(e.getMessage());

						}

						while (fid_tFileInputDelimited_1 != null && fid_tFileInputDelimited_1.nextRecord()) {
							rowstate_tFileInputDelimited_1.reset();

							row1 = null;

							boolean whetherReject_tFileInputDelimited_1 = false;
							row1 = new row1Struct();
							try {

								int columnIndexWithD_tFileInputDelimited_1 = 0;

								String temp = "";

								columnIndexWithD_tFileInputDelimited_1 = 0;

								temp = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);
								if (temp.length() > 0) {

									try {

										row1.id_tiempo = ParserUtils.parseTo_BigDecimal(temp);

									} catch (java.lang.Exception ex_tFileInputDelimited_1) {
										globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE",
												ex_tFileInputDelimited_1.getMessage());
										rowstate_tFileInputDelimited_1.setException(new RuntimeException(String.format(
												"Couldn't parse value for column '%s' in '%s', value is '%s'. Details: %s",
												"id_tiempo", "row1", temp, ex_tFileInputDelimited_1),
												ex_tFileInputDelimited_1));
									}

								} else {

									row1.id_tiempo = null;

								}

								columnIndexWithD_tFileInputDelimited_1 = 1;

								temp = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);
								if (temp.length() > 0) {

									try {

										row1.id_producto = ParserUtils.parseTo_BigDecimal(temp);

									} catch (java.lang.Exception ex_tFileInputDelimited_1) {
										globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE",
												ex_tFileInputDelimited_1.getMessage());
										rowstate_tFileInputDelimited_1.setException(new RuntimeException(String.format(
												"Couldn't parse value for column '%s' in '%s', value is '%s'. Details: %s",
												"id_producto", "row1", temp, ex_tFileInputDelimited_1),
												ex_tFileInputDelimited_1));
									}

								} else {

									row1.id_producto = null;

								}

								columnIndexWithD_tFileInputDelimited_1 = 2;

								temp = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);
								if (temp.length() > 0) {

									try {

										row1.id_cliente = ParserUtils.parseTo_BigDecimal(temp);

									} catch (java.lang.Exception ex_tFileInputDelimited_1) {
										globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE",
												ex_tFileInputDelimited_1.getMessage());
										rowstate_tFileInputDelimited_1.setException(new RuntimeException(String.format(
												"Couldn't parse value for column '%s' in '%s', value is '%s'. Details: %s",
												"id_cliente", "row1", temp, ex_tFileInputDelimited_1),
												ex_tFileInputDelimited_1));
									}

								} else {

									row1.id_cliente = null;

								}

								columnIndexWithD_tFileInputDelimited_1 = 3;

								temp = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);
								if (temp.length() > 0) {

									try {

										row1.id_sucursal = ParserUtils.parseTo_BigDecimal(temp);

									} catch (java.lang.Exception ex_tFileInputDelimited_1) {
										globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE",
												ex_tFileInputDelimited_1.getMessage());
										rowstate_tFileInputDelimited_1.setException(new RuntimeException(String.format(
												"Couldn't parse value for column '%s' in '%s', value is '%s'. Details: %s",
												"id_sucursal", "row1", temp, ex_tFileInputDelimited_1),
												ex_tFileInputDelimited_1));
									}

								} else {

									row1.id_sucursal = null;

								}

								columnIndexWithD_tFileInputDelimited_1 = 4;

								temp = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);
								if (temp.length() > 0) {

									try {

										row1.cantidad = ParserUtils.parseTo_BigDecimal(temp);

									} catch (java.lang.Exception ex_tFileInputDelimited_1) {
										globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE",
												ex_tFileInputDelimited_1.getMessage());
										rowstate_tFileInputDelimited_1.setException(new RuntimeException(String.format(
												"Couldn't parse value for column '%s' in '%s', value is '%s'. Details: %s",
												"cantidad", "row1", temp, ex_tFileInputDelimited_1),
												ex_tFileInputDelimited_1));
									}

								} else {

									row1.cantidad = null;

								}

								columnIndexWithD_tFileInputDelimited_1 = 5;

								temp = fid_tFileInputDelimited_1.get(columnIndexWithD_tFileInputDelimited_1);
								if (temp.length() > 0) {

									try {

										row1.total = ParserUtils.parseTo_BigDecimal(temp);

									} catch (java.lang.Exception ex_tFileInputDelimited_1) {
										globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE",
												ex_tFileInputDelimited_1.getMessage());
										rowstate_tFileInputDelimited_1.setException(new RuntimeException(String.format(
												"Couldn't parse value for column '%s' in '%s', value is '%s'. Details: %s",
												"total", "row1", temp, ex_tFileInputDelimited_1),
												ex_tFileInputDelimited_1));
									}

								} else {

									row1.total = null;

								}

								columnIndexWithD_tFileInputDelimited_1 = 6;

								row1.fecha_carga = fid_tFileInputDelimited_1
										.get(columnIndexWithD_tFileInputDelimited_1);

								columnIndexWithD_tFileInputDelimited_1 = 7;

								row1.sistema_carga = fid_tFileInputDelimited_1
										.get(columnIndexWithD_tFileInputDelimited_1);

								if (rowstate_tFileInputDelimited_1.getException() != null) {
									throw rowstate_tFileInputDelimited_1.getException();
								}

							} catch (java.lang.Exception e) {
								globalMap.put("tFileInputDelimited_1_ERROR_MESSAGE", e.getMessage());
								whetherReject_tFileInputDelimited_1 = true;

								System.err.println(e.getMessage());
								row1 = null;

							}

							/**
							 * [tFileInputDelimited_1 begin ] stop
							 */

							/**
							 * [tFileInputDelimited_1 main ] start
							 */

							currentComponent = "tFileInputDelimited_1";

							tos_count_tFileInputDelimited_1++;

							/**
							 * [tFileInputDelimited_1 main ] stop
							 */

							/**
							 * [tFileInputDelimited_1 process_data_begin ] start
							 */

							currentComponent = "tFileInputDelimited_1";

							/**
							 * [tFileInputDelimited_1 process_data_begin ] stop
							 */
// Start of branch "row1"
							if (row1 != null) {

								/**
								 * [tMap_1 main ] start
								 */

								currentComponent = "tMap_1";

								if (execStat) {
									runStat.updateStatOnConnection(iterateId, 1, 1

											, "row1"

									);
								}

								boolean hasCasePrimitiveKeyWithNull_tMap_1 = false;

								// ###############################
								// # Input tables (lookups)
								boolean rejectedInnerJoin_tMap_1 = false;
								boolean mainRowRejected_tMap_1 = false;

								// ###############################
								{ // start of Var scope

									// ###############################
									// # Vars tables

									Var__tMap_1__Struct Var = Var__tMap_1;// ###############################
									// ###############################
									// # Output tables

									fac_venta = null;

// # Output table : 'fac_venta'
									fac_venta_tmp.ID_TIEMPO = row1.id_tiempo;
									fac_venta_tmp.ID_PRODUCTO = row1.id_producto;
									fac_venta_tmp.ID_CLIENTE = row1.id_cliente;
									fac_venta_tmp.ID_SUCURSAL = row1.id_sucursal;
									fac_venta_tmp.CANTIDAD = row1.cantidad;
									fac_venta_tmp.TOTAL = row1.total;
									fac_venta_tmp.FECHA_CARGA = row1.fecha_carga;
									fac_venta_tmp.SISTEMA_CARGA = row1.sistema_carga;
									fac_venta = fac_venta_tmp;
// ###############################

								} // end of Var scope

								rejectedInnerJoin_tMap_1 = false;

								tos_count_tMap_1++;

								/**
								 * [tMap_1 main ] stop
								 */

								/**
								 * [tMap_1 process_data_begin ] start
								 */

								currentComponent = "tMap_1";

								/**
								 * [tMap_1 process_data_begin ] stop
								 */
// Start of branch "fac_venta"
								if (fac_venta != null) {

									/**
									 * [tDBOutput_1 main ] start
									 */

									currentComponent = "tDBOutput_1";

									if (execStat) {
										runStat.updateStatOnConnection(iterateId, 1, 1

												, "fac_venta"

										);
									}

									row2 = null;
									whetherReject_tDBOutput_1 = false;
									pstmt_tDBOutput_1.setBigDecimal(1, fac_venta.ID_TIEMPO);

									pstmt_tDBOutput_1.setBigDecimal(2, fac_venta.ID_PRODUCTO);

									pstmt_tDBOutput_1.setBigDecimal(3, fac_venta.ID_CLIENTE);

									pstmt_tDBOutput_1.setBigDecimal(4, fac_venta.ID_SUCURSAL);

									pstmt_tDBOutput_1.setBigDecimal(5, fac_venta.CANTIDAD);

									pstmt_tDBOutput_1.setBigDecimal(6, fac_venta.TOTAL);

									if (fac_venta.FECHA_CARGA == null) {
										pstmt_tDBOutput_1.setNull(7, java.sql.Types.VARCHAR);
									} else {
										pstmt_tDBOutput_1.setString(7, fac_venta.FECHA_CARGA);
									}

									if (fac_venta.SISTEMA_CARGA == null) {
										pstmt_tDBOutput_1.setNull(8, java.sql.Types.VARCHAR);
									} else {
										pstmt_tDBOutput_1.setString(8, fac_venta.SISTEMA_CARGA);
									}

									pstmt_tDBOutput_1.addBatch();
									nb_line_tDBOutput_1++;
									batchSizeCounter_tDBOutput_1++;
									if (!whetherReject_tDBOutput_1) {
										row2 = new row2Struct();
										row2.ID_TIEMPO = fac_venta.ID_TIEMPO;
										row2.ID_PRODUCTO = fac_venta.ID_PRODUCTO;
										row2.ID_CLIENTE = fac_venta.ID_CLIENTE;
										row2.ID_SUCURSAL = fac_venta.ID_SUCURSAL;
										row2.CANTIDAD = fac_venta.CANTIDAD;
										row2.TOTAL = fac_venta.TOTAL;
										row2.FECHA_CARGA = fac_venta.FECHA_CARGA;
										row2.SISTEMA_CARGA = fac_venta.SISTEMA_CARGA;
									}
									if (batchSize_tDBOutput_1 > 0
											&& batchSize_tDBOutput_1 <= batchSizeCounter_tDBOutput_1) {
										try {
											pstmt_tDBOutput_1.executeBatch();
										} catch (java.sql.BatchUpdateException e_tDBOutput_1) {
											globalMap.put("tDBOutput_1_ERROR_MESSAGE", e_tDBOutput_1.getMessage());
											java.sql.SQLException ne_tDBOutput_1 = e_tDBOutput_1.getNextException(),
													sqle_tDBOutput_1 = null;
											String errormessage_tDBOutput_1;
											if (ne_tDBOutput_1 != null) {
												// build new exception to provide the original cause
												sqle_tDBOutput_1 = new java.sql.SQLException(
														e_tDBOutput_1.getMessage() + "\ncaused by: "
																+ ne_tDBOutput_1.getMessage(),
														ne_tDBOutput_1.getSQLState(), ne_tDBOutput_1.getErrorCode(),
														ne_tDBOutput_1);
												errormessage_tDBOutput_1 = sqle_tDBOutput_1.getMessage();
											} else {
												errormessage_tDBOutput_1 = e_tDBOutput_1.getMessage();
											}

											System.err.println(errormessage_tDBOutput_1);

										}
										tmp_batchUpdateCount_tDBOutput_1 = pstmt_tDBOutput_1.getUpdateCount();
										insertedCount_tDBOutput_1 += (tmp_batchUpdateCount_tDBOutput_1 != -1
												? tmp_batchUpdateCount_tDBOutput_1
												: 0);
										rowsToCommitCount_tDBOutput_1 += (tmp_batchUpdateCount_tDBOutput_1 != -1
												? tmp_batchUpdateCount_tDBOutput_1
												: 0);
										batchSizeCounter_tDBOutput_1 = 0;
									}
									commitCounter_tDBOutput_1++;
									if (commitEvery_tDBOutput_1 <= commitCounter_tDBOutput_1) {
										if (batchSizeCounter_tDBOutput_1 > 0) {
											try {
												pstmt_tDBOutput_1.executeBatch();
											} catch (java.sql.BatchUpdateException e_tDBOutput_1) {
												globalMap.put("tDBOutput_1_ERROR_MESSAGE", e_tDBOutput_1.getMessage());
												java.sql.SQLException ne_tDBOutput_1 = e_tDBOutput_1.getNextException(),
														sqle_tDBOutput_1 = null;
												String errormessage_tDBOutput_1;
												if (ne_tDBOutput_1 != null) {
													// build new exception to provide the original cause
													sqle_tDBOutput_1 = new java.sql.SQLException(
															e_tDBOutput_1.getMessage() + "\ncaused by: "
																	+ ne_tDBOutput_1.getMessage(),
															ne_tDBOutput_1.getSQLState(), ne_tDBOutput_1.getErrorCode(),
															ne_tDBOutput_1);
													errormessage_tDBOutput_1 = sqle_tDBOutput_1.getMessage();
												} else {
													errormessage_tDBOutput_1 = e_tDBOutput_1.getMessage();
												}

												System.err.println(errormessage_tDBOutput_1);

											}
											tmp_batchUpdateCount_tDBOutput_1 = pstmt_tDBOutput_1.getUpdateCount();
											insertedCount_tDBOutput_1 += (tmp_batchUpdateCount_tDBOutput_1 != -1
													? tmp_batchUpdateCount_tDBOutput_1
													: 0);
											rowsToCommitCount_tDBOutput_1 += (tmp_batchUpdateCount_tDBOutput_1 != -1
													? tmp_batchUpdateCount_tDBOutput_1
													: 0);
										}
										if (rowsToCommitCount_tDBOutput_1 != 0) {

										}
										conn_tDBOutput_1.commit();
										if (rowsToCommitCount_tDBOutput_1 != 0) {

											rowsToCommitCount_tDBOutput_1 = 0;
										}
										commitCounter_tDBOutput_1 = 0;
										batchSizeCounter_tDBOutput_1 = 0;
									}

									tos_count_tDBOutput_1++;

									/**
									 * [tDBOutput_1 main ] stop
									 */

									/**
									 * [tDBOutput_1 process_data_begin ] start
									 */

									currentComponent = "tDBOutput_1";

									/**
									 * [tDBOutput_1 process_data_begin ] stop
									 */
// Start of branch "row2"
									if (row2 != null) {

										/**
										 * [tLogRow_1 main ] start
										 */

										currentComponent = "tLogRow_1";

										if (execStat) {
											runStat.updateStatOnConnection(iterateId, 1, 1

													, "row2"

											);
										}

///////////////////////		

										String[] row_tLogRow_1 = new String[8];

										if (row2.ID_TIEMPO != null) { //
											row_tLogRow_1[0] = row2.ID_TIEMPO
													.setScale(0, java.math.RoundingMode.HALF_UP).toPlainString();

										} //

										if (row2.ID_PRODUCTO != null) { //
											row_tLogRow_1[1] = row2.ID_PRODUCTO
													.setScale(0, java.math.RoundingMode.HALF_UP).toPlainString();

										} //

										if (row2.ID_CLIENTE != null) { //
											row_tLogRow_1[2] = row2.ID_CLIENTE
													.setScale(0, java.math.RoundingMode.HALF_UP).toPlainString();

										} //

										if (row2.ID_SUCURSAL != null) { //
											row_tLogRow_1[3] = row2.ID_SUCURSAL
													.setScale(0, java.math.RoundingMode.HALF_UP).toPlainString();

										} //

										if (row2.CANTIDAD != null) { //
											row_tLogRow_1[4] = row2.CANTIDAD.toPlainString();

										} //

										if (row2.TOTAL != null) { //
											row_tLogRow_1[5] = row2.TOTAL.setScale(2, java.math.RoundingMode.HALF_UP)
													.toPlainString();

										} //

										if (row2.FECHA_CARGA != null) { //
											row_tLogRow_1[6] = String.valueOf(row2.FECHA_CARGA);

										} //

										if (row2.SISTEMA_CARGA != null) { //
											row_tLogRow_1[7] = String.valueOf(row2.SISTEMA_CARGA);

										} //

										util_tLogRow_1.addRow(row_tLogRow_1);
										nb_line_tLogRow_1++;
//////

//////                    

///////////////////////    			

										tos_count_tLogRow_1++;

										/**
										 * [tLogRow_1 main ] stop
										 */

										/**
										 * [tLogRow_1 process_data_begin ] start
										 */

										currentComponent = "tLogRow_1";

										/**
										 * [tLogRow_1 process_data_begin ] stop
										 */

										/**
										 * [tLogRow_1 process_data_end ] start
										 */

										currentComponent = "tLogRow_1";

										/**
										 * [tLogRow_1 process_data_end ] stop
										 */

									} // End of branch "row2"

									/**
									 * [tDBOutput_1 process_data_end ] start
									 */

									currentComponent = "tDBOutput_1";

									/**
									 * [tDBOutput_1 process_data_end ] stop
									 */

								} // End of branch "fac_venta"

								/**
								 * [tMap_1 process_data_end ] start
								 */

								currentComponent = "tMap_1";

								/**
								 * [tMap_1 process_data_end ] stop
								 */

							} // End of branch "row1"

							/**
							 * [tFileInputDelimited_1 process_data_end ] start
							 */

							currentComponent = "tFileInputDelimited_1";

							/**
							 * [tFileInputDelimited_1 process_data_end ] stop
							 */

							/**
							 * [tFileInputDelimited_1 end ] start
							 */

							currentComponent = "tFileInputDelimited_1";

						}
					} finally {
						if (!((Object) (((String) globalMap
								.get("tWaitForFile_1_CREATED_FILE"))) instanceof java.io.InputStream)) {
							if (fid_tFileInputDelimited_1 != null) {
								fid_tFileInputDelimited_1.close();
							}
						}
						if (fid_tFileInputDelimited_1 != null) {
							globalMap.put("tFileInputDelimited_1_NB_LINE", fid_tFileInputDelimited_1.getRowNumber());

						}
					}

					ok_Hash.put("tFileInputDelimited_1", true);
					end_Hash.put("tFileInputDelimited_1", System.currentTimeMillis());

					/**
					 * [tFileInputDelimited_1 end ] stop
					 */

					/**
					 * [tMap_1 end ] start
					 */

					currentComponent = "tMap_1";

// ###############################
// # Lookup hashes releasing
// ###############################      

					if (execStat) {
						runStat.updateStat(resourceMap, iterateId, 2, 0, "row1");
					}

					ok_Hash.put("tMap_1", true);
					end_Hash.put("tMap_1", System.currentTimeMillis());

					/**
					 * [tMap_1 end ] stop
					 */

					/**
					 * [tDBOutput_1 end ] start
					 */

					currentComponent = "tDBOutput_1";

					if (batchSizeCounter_tDBOutput_1 > 0) {
						try {
							if (pstmt_tDBOutput_1 != null) {

								pstmt_tDBOutput_1.executeBatch();

							}
						} catch (java.sql.BatchUpdateException e_tDBOutput_1) {
							globalMap.put("tDBOutput_1_ERROR_MESSAGE", e_tDBOutput_1.getMessage());
							java.sql.SQLException ne_tDBOutput_1 = e_tDBOutput_1.getNextException(),
									sqle_tDBOutput_1 = null;
							String errormessage_tDBOutput_1;
							if (ne_tDBOutput_1 != null) {
								// build new exception to provide the original cause
								sqle_tDBOutput_1 = new java.sql.SQLException(
										e_tDBOutput_1.getMessage() + "\ncaused by: " + ne_tDBOutput_1.getMessage(),
										ne_tDBOutput_1.getSQLState(), ne_tDBOutput_1.getErrorCode(), ne_tDBOutput_1);
								errormessage_tDBOutput_1 = sqle_tDBOutput_1.getMessage();
							} else {
								errormessage_tDBOutput_1 = e_tDBOutput_1.getMessage();
							}

							System.err.println(errormessage_tDBOutput_1);

						}
						if (pstmt_tDBOutput_1 != null) {
							tmp_batchUpdateCount_tDBOutput_1 = pstmt_tDBOutput_1.getUpdateCount();

							insertedCount_tDBOutput_1

									+= (tmp_batchUpdateCount_tDBOutput_1 != -1 ? tmp_batchUpdateCount_tDBOutput_1 : 0);
							rowsToCommitCount_tDBOutput_1 += (tmp_batchUpdateCount_tDBOutput_1 != -1
									? tmp_batchUpdateCount_tDBOutput_1
									: 0);
						}
					}
					if (pstmt_tDBOutput_1 != null) {

						pstmt_tDBOutput_1.close();
						resourceMap.remove("pstmt_tDBOutput_1");

					}
					resourceMap.put("statementClosed_tDBOutput_1", true);
					if (commitCounter_tDBOutput_1 > 0 && rowsToCommitCount_tDBOutput_1 != 0) {

					}
					conn_tDBOutput_1.commit();
					if (commitCounter_tDBOutput_1 > 0 && rowsToCommitCount_tDBOutput_1 != 0) {

						rowsToCommitCount_tDBOutput_1 = 0;
					}
					commitCounter_tDBOutput_1 = 0;

					conn_tDBOutput_1.close();

					resourceMap.put("finish_tDBOutput_1", true);

					nb_line_deleted_tDBOutput_1 = nb_line_deleted_tDBOutput_1 + deletedCount_tDBOutput_1;
					nb_line_update_tDBOutput_1 = nb_line_update_tDBOutput_1 + updatedCount_tDBOutput_1;
					nb_line_inserted_tDBOutput_1 = nb_line_inserted_tDBOutput_1 + insertedCount_tDBOutput_1;
					nb_line_rejected_tDBOutput_1 = nb_line_rejected_tDBOutput_1 + rejectedCount_tDBOutput_1;

					globalMap.put("tDBOutput_1_NB_LINE", nb_line_tDBOutput_1);
					globalMap.put("tDBOutput_1_NB_LINE_UPDATED", nb_line_update_tDBOutput_1);
					globalMap.put("tDBOutput_1_NB_LINE_INSERTED", nb_line_inserted_tDBOutput_1);
					globalMap.put("tDBOutput_1_NB_LINE_DELETED", nb_line_deleted_tDBOutput_1);
					globalMap.put("tDBOutput_1_NB_LINE_REJECTED", nb_line_rejected_tDBOutput_1);

					if (execStat) {
						runStat.updateStat(resourceMap, iterateId, 2, 0, "fac_venta");
					}

					ok_Hash.put("tDBOutput_1", true);
					end_Hash.put("tDBOutput_1", System.currentTimeMillis());

					if (execStat) {
						runStat.updateStatOnConnection("OnComponentOk1", 0, "ok");
					}
					tFileCopy_1Process(globalMap);

					/**
					 * [tDBOutput_1 end ] stop
					 */

					/**
					 * [tLogRow_1 end ] start
					 */

					currentComponent = "tLogRow_1";

//////

					java.io.PrintStream consoleOut_tLogRow_1 = null;
					if (globalMap.get("tLogRow_CONSOLE") != null) {
						consoleOut_tLogRow_1 = (java.io.PrintStream) globalMap.get("tLogRow_CONSOLE");
					} else {
						consoleOut_tLogRow_1 = new java.io.PrintStream(new java.io.BufferedOutputStream(System.out));
						globalMap.put("tLogRow_CONSOLE", consoleOut_tLogRow_1);
					}

					consoleOut_tLogRow_1.println(util_tLogRow_1.format().toString());
					consoleOut_tLogRow_1.flush();
//////
					globalMap.put("tLogRow_1_NB_LINE", nb_line_tLogRow_1);

///////////////////////    			

					if (execStat) {
						runStat.updateStat(resourceMap, iterateId, 2, 0, "row2");
					}

					ok_Hash.put("tLogRow_1", true);
					end_Hash.put("tLogRow_1", System.currentTimeMillis());

					/**
					 * [tLogRow_1 end ] stop
					 */

					if (execStat) {
						runStat.updateStatOnConnection("iterate1", 2, "exec" + NB_ITERATE_tFileInputDelimited_1);
					}

					/**
					 * [tWaitForFile_1 process_data_end ] start
					 */

					currentComponent = "tWaitForFile_1";

					/**
					 * [tWaitForFile_1 process_data_end ] stop
					 */

					/**
					 * [tWaitForFile_1 end ] start
					 */

					currentComponent = "tWaitForFile_1";

					if (false) {
						break;
					}
				}

				ok_Hash.put("tWaitForFile_1", true);
				end_Hash.put("tWaitForFile_1", System.currentTimeMillis());

				/**
				 * [tWaitForFile_1 end ] stop
				 */
			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tWaitForFile_1 finally ] start
				 */

				currentComponent = "tWaitForFile_1";

				/**
				 * [tWaitForFile_1 finally ] stop
				 */

				/**
				 * [tFileInputDelimited_1 finally ] start
				 */

				currentComponent = "tFileInputDelimited_1";

				/**
				 * [tFileInputDelimited_1 finally ] stop
				 */

				/**
				 * [tMap_1 finally ] start
				 */

				currentComponent = "tMap_1";

				/**
				 * [tMap_1 finally ] stop
				 */

				/**
				 * [tDBOutput_1 finally ] start
				 */

				currentComponent = "tDBOutput_1";

				try {
					if (resourceMap.get("statementClosed_tDBOutput_1") == null) {
						java.sql.PreparedStatement pstmtToClose_tDBOutput_1 = null;
						if ((pstmtToClose_tDBOutput_1 = (java.sql.PreparedStatement) resourceMap
								.remove("pstmt_tDBOutput_1")) != null) {
							pstmtToClose_tDBOutput_1.close();
						}
					}
				} finally {
					if (resourceMap.get("finish_tDBOutput_1") == null) {
						java.sql.Connection ctn_tDBOutput_1 = null;
						if ((ctn_tDBOutput_1 = (java.sql.Connection) resourceMap.get("conn_tDBOutput_1")) != null) {
							try {
								ctn_tDBOutput_1.close();
							} catch (java.sql.SQLException sqlEx_tDBOutput_1) {
								String errorMessage_tDBOutput_1 = "failed to close the connection in tDBOutput_1 :"
										+ sqlEx_tDBOutput_1.getMessage();
								System.err.println(errorMessage_tDBOutput_1);
							}
						}
					}
				}

				/**
				 * [tDBOutput_1 finally ] stop
				 */

				/**
				 * [tLogRow_1 finally ] start
				 */

				currentComponent = "tLogRow_1";

				/**
				 * [tLogRow_1 finally ] stop
				 */

			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tWaitForFile_1_SUBPROCESS_STATE", 1);
	}

	public void tFileCopy_1Process(final java.util.Map<String, Object> globalMap) throws TalendException {
		globalMap.put("tFileCopy_1_SUBPROCESS_STATE", 0);

		final boolean execStat = this.execStat;

		String iterateId = "";

		String currentComponent = "";
		java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

		try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { // start the resume
				globalResumeTicket = true;

				/**
				 * [tFileCopy_1 begin ] start
				 */

				ok_Hash.put("tFileCopy_1", false);
				start_Hash.put("tFileCopy_1", System.currentTimeMillis());

				currentComponent = "tFileCopy_1";

				int tos_count_tFileCopy_1 = 0;

				/**
				 * [tFileCopy_1 begin ] stop
				 */

				/**
				 * [tFileCopy_1 main ] start
				 */

				currentComponent = "tFileCopy_1";

				String srcFileName_tFileCopy_1 = ((String) globalMap.get("tWaitForFile_1_CREATED_FILE"));

				java.io.File srcFile_tFileCopy_1 = new java.io.File(srcFileName_tFileCopy_1);

				// here need check first, before mkdirs().
				if (!srcFile_tFileCopy_1.exists() || !srcFile_tFileCopy_1.isFile()) {
					String errorMessageFileDoesnotExistsOrIsNotAFile_tFileCopy_1 = String
							.format("The source File \"%s\" does not exist or is not a file.", srcFileName_tFileCopy_1);
					System.err.println(errorMessageFileDoesnotExistsOrIsNotAFile_tFileCopy_1);
					globalMap.put("tFileCopy_1_ERROR_MESSAGE", errorMessageFileDoesnotExistsOrIsNotAFile_tFileCopy_1);
				}
				String desDirName_tFileCopy_1 = "C:/Users/rober/Desktop/paste,eria/ventas/Procesados";

				String desFileName_tFileCopy_1 = srcFile_tFileCopy_1.getName();

				if (desFileName_tFileCopy_1 != null && ("").equals(desFileName_tFileCopy_1.trim())) {
					desFileName_tFileCopy_1 = "NewName.temp";
				}

				java.io.File desFile_tFileCopy_1 = new java.io.File(desDirName_tFileCopy_1, desFileName_tFileCopy_1);

				if (!srcFile_tFileCopy_1.getPath().equals(desFile_tFileCopy_1.getPath())) {
					java.io.File parentFile_tFileCopy_1 = desFile_tFileCopy_1.getParentFile();

					if (parentFile_tFileCopy_1 != null && !parentFile_tFileCopy_1.exists()) {
						parentFile_tFileCopy_1.mkdirs();
					}
					try {
						org.talend.FileCopy.copyFile(srcFile_tFileCopy_1.getPath(), desFile_tFileCopy_1.getPath(), true,
								false);
					} catch (Exception e) {
						globalMap.put("tFileCopy_1_ERROR_MESSAGE", e.getMessage());
						System.err.println("tFileCopy_1 " + e.getMessage());
					}
					java.io.File isRemoved_tFileCopy_1 = new java.io.File(
							((String) globalMap.get("tWaitForFile_1_CREATED_FILE")));
					if (isRemoved_tFileCopy_1.exists()) {
						String errorMessageCouldNotRemoveFile_tFileCopy_1 = String.format(
								"tFileCopy_1 - The source file \"%s\" could not be removed from the folder because it is open or you only have read-only rights.",
								srcFileName_tFileCopy_1);
						System.err.println(errorMessageCouldNotRemoveFile_tFileCopy_1 + "\n");
						globalMap.put("tFileCopy_1_ERROR_MESSAGE", errorMessageCouldNotRemoveFile_tFileCopy_1);
					}

				}
				globalMap.put("tFileCopy_1_DESTINATION_FILEPATH", desFile_tFileCopy_1.getPath());
				globalMap.put("tFileCopy_1_DESTINATION_FILENAME", desFile_tFileCopy_1.getName());

				globalMap.put("tFileCopy_1_SOURCE_DIRECTORY", srcFile_tFileCopy_1.getParent());
				globalMap.put("tFileCopy_1_DESTINATION_DIRECTORY", desFile_tFileCopy_1.getParent());

				tos_count_tFileCopy_1++;

				/**
				 * [tFileCopy_1 main ] stop
				 */

				/**
				 * [tFileCopy_1 process_data_begin ] start
				 */

				currentComponent = "tFileCopy_1";

				/**
				 * [tFileCopy_1 process_data_begin ] stop
				 */

				/**
				 * [tFileCopy_1 process_data_end ] start
				 */

				currentComponent = "tFileCopy_1";

				/**
				 * [tFileCopy_1 process_data_end ] stop
				 */

				/**
				 * [tFileCopy_1 end ] start
				 */

				currentComponent = "tFileCopy_1";

				ok_Hash.put("tFileCopy_1", true);
				end_Hash.put("tFileCopy_1", System.currentTimeMillis());

				/**
				 * [tFileCopy_1 end ] stop
				 */
			} // end the resume

		} catch (java.lang.Exception e) {

			TalendException te = new TalendException(e, currentComponent, globalMap);

			throw te;
		} catch (java.lang.Error error) {

			runStat.stopThreadStat();

			throw error;
		} finally {

			try {

				/**
				 * [tFileCopy_1 finally ] start
				 */

				currentComponent = "tFileCopy_1";

				/**
				 * [tFileCopy_1 finally ] stop
				 */
			} catch (java.lang.Exception e) {
				// ignore
			} catch (java.lang.Error error) {
				// ignore
			}
			resourceMap = null;
		}

		globalMap.put("tFileCopy_1_SUBPROCESS_STATE", 1);
	}

	public String resuming_logs_dir_path = null;
	public String resuming_checkpoint_path = null;
	public String parent_part_launcher = null;
	private String resumeEntryMethodName = null;
	private boolean globalResumeTicket = false;

	public boolean watch = false;
	// portStats is null, it means don't execute the statistics
	public Integer portStats = null;
	public int portTraces = 4334;
	public String clientHost;
	public String defaultClientHost = "localhost";
	public String contextStr = "Default";
	public boolean isDefaultContext = true;
	public String pid = "0";
	public String rootPid = null;
	public String fatherPid = null;
	public String fatherNode = null;
	public long startTime = 0;
	public boolean isChildJob = false;
	public String log4jLevel = "";

	private boolean enableLogStash;

	private boolean execStat = true;

	private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
		protected java.util.Map<String, String> initialValue() {
			java.util.Map<String, String> threadRunResultMap = new java.util.HashMap<String, String>();
			threadRunResultMap.put("errorCode", null);
			threadRunResultMap.put("status", "");
			return threadRunResultMap;
		};
	};

	protected PropertiesWithType context_param = new PropertiesWithType();
	public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

	public String status = "";

	public static void main(String[] args) {
		final fac_ventas fac_ventasClass = new fac_ventas();

		int exitCode = fac_ventasClass.runJobInTOS(args);

		System.exit(exitCode);
	}

	public String[][] runJob(String[] args) {

		int exitCode = runJobInTOS(args);
		String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

		return bufferValue;
	}

	public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;

		return hastBufferOutput;
	}

	public int runJobInTOS(String[] args) {
		// reset status
		status = "";

		String lastStr = "";
		for (String arg : args) {
			if (arg.equalsIgnoreCase("--context_param")) {
				lastStr = arg;
			} else if (lastStr.equals("")) {
				evalParam(arg);
			} else {
				evalParam(lastStr + " " + arg);
				lastStr = "";
			}
		}
		enableLogStash = "true".equalsIgnoreCase(System.getProperty("audit.enabled"));

		if (clientHost == null) {
			clientHost = defaultClientHost;
		}

		if (pid == null || "0".equals(pid)) {
			pid = TalendString.getAsciiRandomString(6);
		}

		if (rootPid == null) {
			rootPid = pid;
		}
		if (fatherPid == null) {
			fatherPid = pid;
		} else {
			isChildJob = true;
		}

		if (portStats != null) {
			// portStats = -1; //for testing
			if (portStats < 0 || portStats > 65535) {
				// issue:10869, the portStats is invalid, so this client socket can't open
				System.err.println("The statistics socket port " + portStats + " is invalid.");
				execStat = false;
			}
		} else {
			execStat = false;
		}
		boolean inOSGi = routines.system.BundleUtils.inOSGi();

		if (inOSGi) {
			java.util.Dictionary<String, Object> jobProperties = routines.system.BundleUtils.getJobProperties(jobName);

			if (jobProperties != null && jobProperties.get("context") != null) {
				contextStr = (String) jobProperties.get("context");
			}
		}

		try {
			// call job/subjob with an existing context, like: --context=production. if
			// without this parameter, there will use the default context instead.
			java.io.InputStream inContext = fac_ventas.class.getClassLoader()
					.getResourceAsStream("dm_pasteleria/fac_ventas_0_1/contexts/" + contextStr + ".properties");
			if (inContext == null) {
				inContext = fac_ventas.class.getClassLoader()
						.getResourceAsStream("config/contexts/" + contextStr + ".properties");
			}
			if (inContext != null) {
				try {
					// defaultProps is in order to keep the original context value
					if (context != null && context.isEmpty()) {
						defaultProps.load(inContext);
						context = new ContextProperties(defaultProps);
					}
				} finally {
					inContext.close();
				}
			} else if (!isDefaultContext) {
				// print info and job continue to run, for case: context_param is not empty.
				System.err.println("Could not find the context " + contextStr);
			}

			if (!context_param.isEmpty()) {
				context.putAll(context_param);
				// set types for params from parentJobs
				for (Object key : context_param.keySet()) {
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
			}
			class ContextProcessing {
				private void processContext_0() {
				}

				public void processAllContext() {
					processContext_0();
				}
			}

			new ContextProcessing().processAllContext();
		} catch (java.io.IOException ie) {
			System.err.println("Could not load context " + contextStr);
			ie.printStackTrace();
		}

		// get context value from parent directly
		if (parentContextMap != null && !parentContextMap.isEmpty()) {
		}

		// Resume: init the resumeUtil
		resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
		resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
		resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
		// Resume: jobStart
		resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "",
				"", "", "", "", resumeUtil.convertToJsonText(context, parametersToEncrypt));

		if (execStat) {
			try {
				runStat.openSocket(!isChildJob);
				runStat.setAllPID(rootPid, fatherPid, pid, jobName);
				runStat.startThreadStat(clientHost, portStats);
				runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
			} catch (java.io.IOException ioException) {
				ioException.printStackTrace();
			}
		}

		java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
		globalMap.put("concurrentHashMap", concurrentHashMap);

		long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		long endUsedMemory = 0;
		long end = 0;

		startTime = System.currentTimeMillis();

		this.globalResumeTicket = true;// to run tPreJob

		this.globalResumeTicket = false;// to run others jobs

		try {
			errorCode = null;
			tWaitForFile_1Process(globalMap);
			if (!"failure".equals(status)) {
				status = "end";
			}
		} catch (TalendException e_tWaitForFile_1) {
			globalMap.put("tWaitForFile_1_SUBPROCESS_STATE", -1);

			e_tWaitForFile_1.printStackTrace();

		}

		this.globalResumeTicket = true;// to run tPostJob

		end = System.currentTimeMillis();

		if (watch) {
			System.out.println((end - startTime) + " milliseconds");
		}

		endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
		if (false) {
			System.out.println((endUsedMemory - startUsedMemory) + " bytes memory increase when running : fac_ventas");
		}

		if (execStat) {
			runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
			runStat.stopThreadStat();
		}
		int returnCode = 0;

		if (errorCode == null) {
			returnCode = status != null && status.equals("failure") ? 1 : 0;
		} else {
			returnCode = errorCode.intValue();
		}
		resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "",
				"" + returnCode, "", "", "");

		return returnCode;

	}

	// only for OSGi env
	public void destroy() {

	}

	private java.util.Map<String, Object> getSharedConnections4REST() {
		java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();

		return connections;
	}

	private void evalParam(String arg) {
		if (arg.startsWith("--resuming_logs_dir_path")) {
			resuming_logs_dir_path = arg.substring(25);
		} else if (arg.startsWith("--resuming_checkpoint_path")) {
			resuming_checkpoint_path = arg.substring(27);
		} else if (arg.startsWith("--parent_part_launcher")) {
			parent_part_launcher = arg.substring(23);
		} else if (arg.startsWith("--watch")) {
			watch = true;
		} else if (arg.startsWith("--stat_port=")) {
			String portStatsStr = arg.substring(12);
			if (portStatsStr != null && !portStatsStr.equals("null")) {
				portStats = Integer.parseInt(portStatsStr);
			}
		} else if (arg.startsWith("--trace_port=")) {
			portTraces = Integer.parseInt(arg.substring(13));
		} else if (arg.startsWith("--client_host=")) {
			clientHost = arg.substring(14);
		} else if (arg.startsWith("--context=")) {
			contextStr = arg.substring(10);
			isDefaultContext = false;
		} else if (arg.startsWith("--father_pid=")) {
			fatherPid = arg.substring(13);
		} else if (arg.startsWith("--root_pid=")) {
			rootPid = arg.substring(11);
		} else if (arg.startsWith("--father_node=")) {
			fatherNode = arg.substring(14);
		} else if (arg.startsWith("--pid=")) {
			pid = arg.substring(6);
		} else if (arg.startsWith("--context_type")) {
			String keyValue = arg.substring(15);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.setContextType(keyValue.substring(0, index),
							replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1));
				}

			}

		} else if (arg.startsWith("--context_param")) {
			String keyValue = arg.substring(16);
			int index = -1;
			if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
				if (fatherPid == null) {
					context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
				} else { // the subjob won't escape the especial chars
					context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1));
				}
			}
		} else if (arg.startsWith("--log4jLevel=")) {
			log4jLevel = arg.substring(13);
		} else if (arg.startsWith("--audit.enabled") && arg.contains("=")) {// for trunjob call
			final int equal = arg.indexOf('=');
			final String key = arg.substring("--".length(), equal);
			System.setProperty(key, arg.substring(equal + 1));
		}
	}

	private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

	private final String[][] escapeChars = { { "\\\\", "\\" }, { "\\n", "\n" }, { "\\'", "\'" }, { "\\r", "\r" },
			{ "\\f", "\f" }, { "\\b", "\b" }, { "\\t", "\t" } };

	private String replaceEscapeChars(String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0], currIndex);
				if (index >= 0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0],
							strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the
			// result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
	}

	public Integer getErrorCode() {
		return errorCode;
	}

	public String getStatus() {
		return status;
	}

	ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 * 102629 characters generated by Talend Open Studio for Data Integration on the
 * 6 de diciembre de 2025, 01:37:09 BOT
 ************************************************************************************************/