
DROP USER dmPasteleria CASCADE;
DROP USER stPasteleria CASCADE;

CREATE USER dmPasteleria IDENTIFIED BY dmPasteleria
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

GRANT RESOURCE TO dmPasteleria;
GRANT CONNECT TO dmPasteleria;


GRANT DBA TO dmPasteleria; 
GRANT UNLIMITED TABLESPACE TO dmPasteleria;

ALTER USER dmPasteleria DEFAULT ROLE ALL;

CREATE USER stPasteleria IDENTIFIED BY stPasteleria
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

GRANT RESOURCE TO stPasteleria;
GRANT CONNECT TO stPasteleria;
GRANT DBA TO stPasteleria;
GRANT UNLIMITED TABLESPACE TO stPasteleria;

ALTER USER stPasteleria DEFAULT ROLE ALL;